
development:
  adapter: postgresql
  database: shipping_dev
  username: postgres
  password: deviantmammothelegantblazer
  host: localhost

test:
  adapter: postgresql
  database: shipping_dev_test
  username: postgres
  password: deviantmammothelegantblazer
  host: localhost

production:
  adapter: postgresql
  database: shipping_dev
  username: richard
  password: root
  host: localhost

staging:
  adapter: postgresql
  database: shipping_staging
  username: richard
  password: root
  host: localhost
